# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61ebf531bffb1b8f7a297456b1aa6ac61522b075a9883ed0e38bc7eefe5f26a055683ebb31952d2b676c097ed28bc5b1aaf570db2939a668f28676678a9b9e7

test:
  secret_key_base: d3da346f1213c9542e56644227fa596bf31a367e19ae703cc3e1b60ee6a87c5b5acf1d7b61d349fd5a34e7236de61769031f8b932d1d2ac235f1ce0d66bf7ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
